definitions:
  app.Response:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/webhook/github:
    post:
      consumes:
      - application/json
      description: Once received, this will add them to the event stream for consumers.
      produces:
      - application/json
      responses:
        "200":
          description: Successful Response
          schema:
            $ref: '#/definitions/app.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/app.Response'
        "404":
          description: Failure Response
          schema:
            $ref: '#/definitions/app.Response'
      summary: This API is there to receive the GitHub events.
      tags:
      - Webhooks
  /healthz:
    get:
      description: Returns the health of this instance.
      produces:
      - application/json
      responses:
        "200":
          description: Healthy
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: This API is there to receive the health of this instance.
      tags:
      - Health
swagger: "2.0"
